Caches

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,13 +23,15 @@ jobs:
         uses: actions/cache@v3
         with:
           path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-postgres
+          key: ${{ runner.os }}-pg-ferret
           restore-keys: |
-            ${{ runner.os }}-postgres
+            ${{ runner.os }}-pg-ferret
+
+      # Build postgres
 
       - name: Load Docker cache
         if: steps.cache-docker-layers.outputs.cache-hit == 'true'
-        run: docker load -i /tmp/.buildx-cache/docker-image.tar || echo "Cache not found, proceeding without it"
+        run: docker load -i /tmp/.buildx-cache/postgres.tar || echo "Cache not found, proceeding without it"
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
@@ -46,17 +48,31 @@ jobs:
           docker push ${{ secrets.DOCKER_USERNAME }}/pg-ferret-postgres-16:latest
 
       - name: Save Docker image
-        run: docker save pg-ferret-postgres-16:latest -o /tmp/.buildx-cache/docker-image.tar
+        run: docker save pg-ferret-postgres-16:latest -o /tmp/.buildx-cache/postgres.tar
+
+      # - name: Save cache
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: /tmp/.buildx-cache/postgres.tar
+      #     key: ${{ runner.os }}-postgres
+
+      # Build PG Ferret
+
+      - name: Load Docker cache
+        if: steps.cache-docker-layers.outputs.cache-hit == 'true'
+        run: docker load -i /tmp/.buildx-cache/pg-ferret.tar || echo "Cache not found, proceeding without it"
+
+      - name: Build Docker image with pg-ferret-postgres-16 base
+        run: docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache,mode=max --tag cbellew/pg-ferret:latest --push .
+
+      - name: Save Docker image
+        run: docker save cbellew/pg-ferret:latest -o /tmp/.buildx-cache/pg-ferret.tar
 
       - name: Save cache
         uses: actions/cache@v3
         with:
           path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-postgres
-
-      - name: Build Docker image with pg-ferret-postgres-16 base
-        run: |
-          docker buildx build --tag cbellew/pg-ferret:latest --push .
+          key: ${{ runner.os }}-pg-ferret
 
       - name: Logout from Docker Hub
         run: docker logout
